=begin
#SignRequest API

#API for SignRequest.com

OpenAPI spec version: v1
Contact: tech-support@signrequest.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11

=end

# Common files
require 'fsp_signrequest_client/api_client'
require 'fsp_signrequest_client/api_error'
require 'fsp_signrequest_client/version'
require 'fsp_signrequest_client/configuration'

# Models
require 'fsp_signrequest_client/models/auth_token'
require 'fsp_signrequest_client/models/document'
require 'fsp_signrequest_client/models/document_attachment'
require 'fsp_signrequest_client/models/document_search'
require 'fsp_signrequest_client/models/document_signer_template_conf'
require 'fsp_signrequest_client/models/document_signing_log'
require 'fsp_signrequest_client/models/document_signrequest'
require 'fsp_signrequest_client/models/document_team'
require 'fsp_signrequest_client/models/event'
require 'fsp_signrequest_client/models/file_from_sf'
require 'fsp_signrequest_client/models/inline_document_signer_integration_data'
require 'fsp_signrequest_client/models/inline_integration_data'
require 'fsp_signrequest_client/models/inline_prefill_tags'
require 'fsp_signrequest_client/models/inline_response_200'
require 'fsp_signrequest_client/models/inline_response_200_1'
require 'fsp_signrequest_client/models/inline_response_200_2'
require 'fsp_signrequest_client/models/inline_response_200_3'
require 'fsp_signrequest_client/models/inline_response_200_4'
require 'fsp_signrequest_client/models/inline_response_200_5'
require 'fsp_signrequest_client/models/inline_response_200_6'
require 'fsp_signrequest_client/models/inline_response_200_7'
require 'fsp_signrequest_client/models/inline_response_200_8'
require 'fsp_signrequest_client/models/inline_response_200_9'
require 'fsp_signrequest_client/models/inline_response_201'
require 'fsp_signrequest_client/models/inline_response_201_1'
require 'fsp_signrequest_client/models/inline_sign_request'
require 'fsp_signrequest_client/models/inline_team'
require 'fsp_signrequest_client/models/inline_team_member'
require 'fsp_signrequest_client/models/invite_member'
require 'fsp_signrequest_client/models/placeholder'
require 'fsp_signrequest_client/models/required_attachment'
require 'fsp_signrequest_client/models/sign_request'
require 'fsp_signrequest_client/models/sign_request_quick_create'
require 'fsp_signrequest_client/models/signer'
require 'fsp_signrequest_client/models/signer_attachment'
require 'fsp_signrequest_client/models/signer_inputs'
require 'fsp_signrequest_client/models/signing_log'
require 'fsp_signrequest_client/models/team'
require 'fsp_signrequest_client/models/team_member'
require 'fsp_signrequest_client/models/template'
require 'fsp_signrequest_client/models/user'
require 'fsp_signrequest_client/models/webhook_subscription'

# APIs
require 'fsp_signrequest_client/api/api_tokens_api'
require 'fsp_signrequest_client/api/document_attachments_api'
require 'fsp_signrequest_client/api/documents_api'
require 'fsp_signrequest_client/api/documents_search_api'
require 'fsp_signrequest_client/api/events_api'
require 'fsp_signrequest_client/api/signrequest_quick_create_api'
require 'fsp_signrequest_client/api/signrequests_api'
require 'fsp_signrequest_client/api/team_members_api'
require 'fsp_signrequest_client/api/teams_api'
require 'fsp_signrequest_client/api/templates_api'
require 'fsp_signrequest_client/api/webhooks_api'

module SignRequestClient
  class << self
    # Customize default settings for the SDK using block.
    #   SignRequestClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
